// others/services/fe-angular-be-springboot-db-sql-mysql/fe-angular-be-springboot-db-sql-mysql_FE/src/app/components/hello-world/hello-world.component.ts
import { Component, OnInit } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { ApiService } from '../../services/api/api.service';
import { UuidService } from '../../services/uuid/uuid.service';
import { HelloWorldDto } from '../../dtos/HelloWorldDto';


@Component({
  selector: 'hello-world',
  standalone: true,
  imports: [RouterOutlet],
  templateUrl: './hello-world.component.html',
  styleUrl: './hello-world.component.css'
})
export class HelloWorldComponent implements OnInit{

  message: string = "";
  idBe: string = "";
  portBe: string = "";
  idFe: string = "";
  portFe: string = "";

  constructor(private apiService: ApiService, private uuidSevice: UuidService) {}

  ngOnInit(): void {
    this.idFe = this.uuidSevice.getUUID();
    this.portFe = window.location.port;

    let response = this.apiService.getMessage();
    response.subscribe((helloWorldDto: HelloWorldDto)=>{      
      this.message = helloWorldDto.text;
      this.idBe = helloWorldDto.idBe;
      this.portBe = helloWorldDto.portBe;
    });
  }
  
}

<ul>
    <li>
        <span><b>Database Message: </b></span>
        <span> {{message}} </span>
    </li>
    <li>
        <span><b>Back-End Id: </b></span>
        <span> {{idBe}} </span>
    </li>
    <li>
        <span><b>Back-End Port: </b></span>
        <span> {{portBe}} </span>
    </li>
    <li>
        <span><b>Front-End Id: </b></span>
        <span> {{idFe}} </span>
    </li>
    <li>
        <span><b>Front-End Port: </b></span>
        <span> {{portFe}} </span>
    </li>
</ul>

// others/services/fe-react-be-springboot-db-sql-mysql/fe-react-be-springboot-db-sql-mysql_FE/src/components/HelloWorld.js
import { useState, useEffect } from "react";
import getFixedUUID from "../services/uuidService";

function HelloWorld() {

  const [message, setMessage] = useState("");
  const [idBe, setIdBe] = useState("");
  const [portBe, setPortBe] = useState("");
  const [idFe, setIdFe] = useState("");
  const portFe = window.location.port;

  useEffect(() =>{

    const uuid = getFixedUUID();
    setIdFe(uuid);
    
    const fetchData = async () => {

      const response = await fetch("http://localhost:8081/message/1");
      const result = await response.json();
      setMessage(result.text);
      setIdBe(result.idBe);
      setPortBe(result.portBe);

    };

    fetchData();

  }, []);

  return (
    <ul>
      <li>
          <span><b>Database Message: </b></span>
          <span> {message} </span>
      </li>
      <li>
          <span><b>Back-End Id: </b></span>
          <span> {idBe} </span>
      </li>
      <li>
          <span><b>Back-End Port: </b></span>
          <span> {portBe} </span>
      </li>
      <li>
          <span><b>Front-End Id: </b></span>
          <span> {idFe} </span>
      </li>
      <li>
          <span><b>Front-End Port: </b></span>
          <span> {portFe} </span>
      </li>
    </ul>
  );

}

export default HelloWorld;
